version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: '9411'

  # zipkin:
  #   container_name: zipkin
  #   image: openzipkin/zipkin
  #   ports:
  #     - 9411:9411

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
