# source: https://hub.docker.com/r/scylladb/scylla/
# Fix: https://forum.scylladb.com/t/running-3-node-scylladb-in-docker/1057/8

# simple docker compose to work locally on macos.
# this is far from being production ready.

# docker-compose up -d
# docker exec -it scylla1 nodetool status

# Step 2: Setup janusgraph, https://university.scylladb.com/courses/the-mutant-monitoring-system-training-course/lessons/a-graph-data-system-powered-by-scylladb-and-janusgraph/
# See janusgraph directory

version: "3"

services:
  scylla1:
    image: scylladb/scylla
    container_name: scylla1
    volumes:
      - ./scylla1:/var/lib/scylla
    command: --smp 1 --overprovisioned 1 --reactor-backend=epoll

  scylla2:
    image: scylladb/scylla
    container_name: scylla2
    command: --seeds=scylla1 --smp 1 --overprovisioned 1 --reactor-backend=epoll
    volumes:
      - ./scylla2:/var/lib/scylla

  scylla3:
    image: scylladb/scylla
    container_name: scylla3
    command: --seeds=scylla1 --smp 1 --overprovisioned 1 --reactor-backend=epoll
    volumes:
      - ./scylla3:/var/lib/scylla
