# docker compose up

services:
  redis:
    container_name: redis
    image: redis
    command: 'redis-server --save 60 1 --loglevel verbose'
    volumes:
      - redis:/data

  redis-readonly:
    image: redis
    depends_on:
      - redis
    container_name: redis-readonly
    command: redis-server --slaveof redis 6379

  backend:
    build: .
    volumes:
      - ./log:/usr/src/app/log
      - ./defaults:/usr/src/app/defaults
      - ./uploads:/usr/src/app/uploads
      - ./locales:/usr/src/app/locales
      - ./config:/usr/src/app/config
    env_file:
      - .env.docker
    ports:
      - 1337:1337
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'

volumes:
  redis:
