# docker compose build && docker compose up

services:
  demo-wl-redis:
    container_name: demo-wl-redis
    image: redis
    command: 'redis-server --save 60 1 --loglevel verbose'
    volumes:
      - redis:/data
    # ports:
    #   - 6379:6379

  demo-wl-redis-readonly:
    image: redis
    depends_on:
      - demo-wl-redis
    container_name: demo-wl-redis-readonly
    command: redis-server --slaveof demo-wl-redis 6379

  demo-wl-backend:
    build: .
    volumes:
      - ./log:/usr/src/app/log
      - ./defaults:/usr/src/app/defaults
      - ./uploads:/usr/src/app/uploads
      - ./locales:/usr/src/app/locales
      - ./config:/usr/src/app/config
    env_file:
      - .env.docker
    ports:
      - 1337:1337
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'

  demo-wl-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: demo-wl-jaeger
    ports:
      #   - 6831:6831/udp
      #   - 6832:6832/udp
      #   - 5778:5778
      - 16686:16686 # WebUI
      #   - 4317:4317
      #   - 4318:4318
      #   - 14250:14250
      #   - 14268:14268
      #   - 14269:14269
      #   - 9411:9411
    environment:
      []
      # COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      # COLLECTOR_ZIPKIN_HOST_PORT: 9411
      # COLLECTOR_OTLP_ENABLED: true

  demo-wl-kc-postgres:
    container_name: demo-wl-kc-postgres
    restart: unless-stopped
    image: postgres:16-alpine
    # ports:
    #   - 5442:5432 # Local access using port 5442
    environment:
      - POSTGRES_PASSWORD=keycloak-db-password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-psqldb:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  demo-wl-keycloak-1:
    depends_on:
      demo-wl-kc-postgres:
        condition: service_healthy
    container_name: demo-wl-keycloak-1
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - 8443:8443 # WebUI (admin)
    volumes:
      - $PWD/keycloak/conf:/conf/:ro # keytool -genkeypair -storepass secured-store-password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore server.keystore
      - $PWD/keycloak/providers:/opt/keycloak/providers/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    command:
      - --verbose
      - start
      - --db=postgres
      - --hostname=localhost
      - --db-url=jdbc:postgresql://demo-wl-kc-postgres:5432/keycloak
      - --db-username=postgres
      - --db-password=keycloak-db-password
      - --https-key-store-file=/conf/server.keystore
      - --https-key-store-password=secured-store-password

  demo-wl-redis-auth-session:
    image: redis
    container_name: demo-wl-redis-auth-session
    ports:
      - 6379:6379
    volumes:
      - redis-auth-session:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis:
  redis-auth-session:
  keycloak-psqldb:
